collections:
  investigators: 

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate


